version: 2.1

orbs:
  python: circleci/python@1.2


jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: PEP8 validation
          command: flake8

  deploy_to_heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a django-lettings web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a django-lettings web
            docker login
            docker push romainmoreldocker/django-lettings:$CIRCLE_SHA1


workflows:
  build_and_test:
    jobs:
    
      - build_and_test

      - deploy_to_heroku:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
