version: 2.1

orbs:
  python: circleci/python@1.2


jobs:

  build_and_test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: DJANGO_SETTINGS_MODULE=local pytest
      - run:
          name: PEP8 validation
          command: flake8

  deploy_to_docker_hub:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push image to Docker_hub
          command: |
            docker login -u ${HUB_NAME} -p ${HUB_PSWD}
            docker build -t ${HUB_NAME}/${IMG_NAME}:$CIRCLE_SHA1 .
            docker push ${HUB_NAME}/${IMG_NAME}:$CIRCLE_SHA1

  deploy_to_heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a ${IMG_NAME} web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${IMG_NAME} web


workflows:
  build_and_test:
    jobs:
    
      - build_and_test

      - deploy_to_docker_hub:
          requires:
            - build_and_test
          filters:
            branches:
              only: main

      - deploy_to_heroku:
          requires:
            - deploy_to_docker_hub
          filters:
            branches:
              only: main
